name: ðŸš€ Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ’» Checkout current pull-request revision code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.DEVOPS_USER_TOKEN }}

      - name: ðŸŸ¢ Configure Bun on runner
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
        
      - name: ðŸ”µ Install Task
        uses: arduino/setup-task@v2
  
      - name: ðŸ’¼ Configure Git user
        run: |
          git config user.name "gbh-devops-bot"
          git config user.email "devops@gbh.com.do"

      - name: ðŸ“¦ Install package dependencies using lockfile
        run: bun install --frozen-lockfile

      - name: ðŸ”¨ Compile binary for supported platforms
        run: |
          task build
          task compress

      - name: ðŸš€ Release a new version
        run: bun release-it --ci
        env:
          GITHUB_TOKEN: ${{ secrets.DEVOPS_USER_TOKEN }}
